use_frameworks!

platform :ios, '8.0'

target 'ZYChartViews_Example' do
  pod 'ZYChartViews', :path => '../'

  target 'ZYChartViews_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
